### ISSUE TITLE
Fixed makefile.morphos

### ISSUE THREAD

**Issue by polluks** [sba1/simplemail#7]
<pre>--- makefile.morphos.bak	2015-12-25 19:28:01 +0100
+++ makefile.morphos	2015-12-25 19:58:51 +0100
@@ -79,6 +79,7 @@
 	popupmenuclass.c \
 	progmonwnd.c \
 	readwnd.c \
+	request.c \
 	searchwnd.c \
 	shutdownwnd.c \
 	smtoolbarclass.c \
@@ -86,10 +87,11 @@
 	signaturecycleclass.c \
 	startupwnd.c \
 	statuswnd.c \
-	subthreads.c \
+	subthreads_amiga.c \
 	support.c \
 	sysprint.c \
 	tcpip.c \
+	timesupport.c \
 	transwndclass.c \
 	utf8stringclass.c \
 	vsnprintf.c
</pre>

**Comment by sba1** [comment]
I've applied your changes. Thanks for your contribution.

If possible, please provide a real commit next time (either pull request or point me to your branch).

**Comment by polluks** [comment]
I see, frohe Weihnachten! :-)
